### PR TITLE
Spreadsheet Updater

### PR DESCRIPTION
**Pull request by Phoeneix**
Github Issue: [#NUM](add link)

### Description

Updated the code for the Hitide spreadsheet updater

### Overview of work done

- Updated the code to get the data for the newest requirements
- Fixed linting and flake8 warnings

### Overview of verification done

- [UMM_V_AUTO script](https://github.com/podaac/tva-automation-tools/actions/runs/9375026777)
- [Repo_Status_Updater script](https://github.com/podaac/tva-automation-tools/actions/runs/9375135374)

## PR checklist:

* [x] Linted
* [x] Updated code
* [ ] Updated changelog
* [x] Tested changes

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

### CODE REVIEW

**Comment by sliu008** [comment]
was there a reason where the naming style was set to camel case?

**Comment by Phoeneix** [comment]
> was there a reason where the naming style was set to camel case?

To be able to make a difference between a function and a variable inside the code by first glance instead of confusing them and taking time to trying to find out where things are coming from.
Note: A function's input parameter seems to be covered by the method's naming style instead of the variable's naming style in pylint though...

**Comment by sliu008** [comment]
> > was there a reason where the naming style was set to camel case?
> 
> To be able to make a difference between a function and a variable inside the code by first glance instead of confusing them and taking time to trying to find out where things are coming from. Note: A function's input parameter seems to be covered by the method's naming style instead of the variable's naming style in pylint though...

i see in the pylintrc the naming style was camel case. Thanks for the explanation on why there was a mix of camel case and snake case. Although im not sure this would make the code more readable since its mixed and standard for python is snake case. Even though we may mix it like this other libraries don't.

**Comment by Phoeneix** [comment]
> > > was there a reason where the naming style was set to camel case?
> > 
> > 
> > To be able to make a difference between a function and a variable inside the code by first glance instead of confusing them and taking time to trying to find out where things are coming from. Note: A function's input parameter seems to be covered by the method's naming style instead of the variable's naming style in pylint though...
> 
> i see in the pylintrc the naming style was camel case. Thanks for the explanation on why there was a mix of camel case and snake case. Although im not sure this would make the code more readable since its mixed and standard for python is snake case. Even though we may mix it like this other libraries don't.

You are right, I somehow missed it. I will change the camelCases to snake_cases too, so it will be consistent in the code.

Edit: Updated

**Comment by jamesfwood** [comment]
@Phoeneix can you pull the latest develop branch into this again and retest everything?
Thanks!

**Review by jamesfwood — CHANGES_REQUESTED** [review]
Merge develop back into this and retest

**Review by jamesfwood — APPROVED** [review]

**Pull request merged**
